
2015-07-10 11:15:35,882 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/PycharmProjects/server_infos/src/srvinfos.py", line 287, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 11:15:46,212 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/PycharmProjects/server_infos/src/srvinfos.py", line 287, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 11:16:42,337 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/PycharmProjects/server_infos/src/srvinfos.py", line 287, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 11:17:20,178 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/PycharmProjects/server_infos/src/srvinfos.py", line 287, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 11:17:30,646 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/PycharmProjects/server_infos/src/srvinfos.py", line 287, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 11:17:44,155 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/PycharmProjects/server_infos/src/srvinfos.py", line 287, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 11:17:55,485 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/PycharmProjects/server_infos/src/srvinfos.py", line 287, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 11:20:46,406 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "srvinfos.py", line 287, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 11:36:31,019 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/PycharmProjects/server_infos/src/srvinfos.py", line 287, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
2015-07-10 11:46:43,532 - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/PycharmProjects/server_infos/src/srvinfos.py", line 286, in chkconfig_info
    ret = subprocess.Popen(["chkconfig", "--list"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
